//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYCDashboard.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Area
    {
        public long AreaId { get; set; }

        [Required(ErrorMessage = "Area Name is required")]
        [Display(Name = "Area")]
        public string AreaName { get; set; }

        [Required(ErrorMessage = "State Name is required")]
        [Display(Name = "State")]
        public int StateId { get; set; }

        [Required(ErrorMessage = "City Name is required")]
        [Display(Name = "City")]
        public int CityId { get; set; }
    
        public virtual City City { get; set; }
        public virtual State State { get; set; }
    }
}
