//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYCDashboard.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BloodRequest()
        {
            this.UserFaviourateBloodRequests = new HashSet<UserFaviourateBloodRequest>();
        }
    
        public long RequestID { get; set; }
        public string PatientName { get; set; }
        public string BloodGroup { get; set; }
        public string GuardianName { get; set; }
        public string GuardianMobileNumber { get; set; }
        public string HospitalName { get; set; }
        public string HospitalNumber { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> PostedDateandtime { get; set; }
        public int CityID { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFaviourateBloodRequest> UserFaviourateBloodRequests { get; set; }
    }
}
