//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYCDashboard.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directory
    {
        public int DirectoryEntryID { get; set; }
        public int DirectoryCategoryID { get; set; }
        public string Name { get; set; }
        public string ServiceProvided { get; set; }
        public int StateID { get; set; }
        public int CityID { get; set; }
        public string AreaLocated { get; set; }
        public string PinCode { get; set; }
        public string MobileNo { get; set; }
        public string Expertise { get; set; }
    
        public virtual City City { get; set; }
        public virtual DirectoryCategory DirectoryCategory { get; set; }
        public virtual State State { get; set; }
    }
}
