//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYCDashboard.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.ItemPictures = new HashSet<ItemPicture>();
            this.UserFaviourateItems = new HashSet<UserFaviourateItem>();
        }
    
        public long ItemID { get; set; }
        public int CategoryID { get; set; }
        public int SubCategoryID { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public string HeadLine { get; set; }
        public string ShortDescription { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> EventStartDateTime { get; set; }
        public Nullable<System.DateTime> EventEndDateTime { get; set; }
        public string Source { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<long> VisitorCount { get; set; }
        public Nullable<int> AddToCalendarCount { get; set; }
        public int CityID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPicture> ItemPictures { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFaviourateItem> UserFaviourateItems { get; set; }
    }
}
