//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYCDashboard.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPicture
    {
        public long ItemPictureID { get; set; }
        public long ItemID { get; set; }
        public string ThumbImageURL { get; set; }
        public string MediumResURL { get; set; }
        public string DetailsFeedURL { get; set; }
        public string WebsiteURL { get; set; }
        public string WallpaperImageURL { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
