//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYCDashboard.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFaviourateItem
    {
        public long colItemFaviourateID { get; set; }
        public long colItemID { get; set; }
        public int colUserID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
